### ISSUE TITLE
Can it support Imputer?

### ISSUE THREAD

**Issue by aitanjupt** [jpmml/jpmml-sparkml#11]
Imputer is supported in JPMML-SkLearn, and it will produce ‘missingValueReplacement’ and 'missingValueTreatment' in PMML, Can jpmml-sparkml support it?

**Comment by vruusmann** [comment]
Apache Spark ML doesn't provide an `Imputer` class: https://issues.apache.org/jira/browse/SPARK-13568 When it becomes available, then it can be implemented very easily. 

What are you using for value imputation now? Some 3rd-party transformations library?

Alternatively, the JPMML-SparkML library could provide its own selection of helper transformations (in addition to `Imputer`, this could include `ContinuousDomain` and `CategoricalDomain` as already "popularized" by the JPMML-SkLearn library). However, such helper transformations should be implemented in Scala (because Apache Spark ML's Java API was materially broken/deficient from the perspective of subclassing base estimator classes), which I'm not too familiar with (at least - yet).

**Comment by sbourzai** [comment]
hi Sir,
Have you tested it for Pyspark ? i tried with pyspark but i've always import Error "No module named : jpmml_sparkml " 
Thanks,
Saad

**Comment by vruusmann** [comment]
@sbourzai You need to adjust your `PYTHONPATH` environment variable. If you follow the README file step-by-step, then everything works just fine: https://github.com/jpmml/jpmml-sparkml-package#pyspark

**Comment by sbourzai** [comment]
Thank you so much!! when i run mvn -Ppyspark i get the jars files and a message : The requested profile "pyspark" could not be activated because it does not exist. 
and when i run # echo $PYHTONPATH : i get /usr/bin/python:/usr/lib/spark/python which  look normal 
but i still have " no module named jpmml_sparkml "

**Comment by vruusmann** [comment]
> when i run mvn -Ppyspark i get the jars files and a message : The requested profile "pyspark" could not be activated because it does not exist.

The "pyspark" profile **does exist**:
https://github.com/jpmml/jpmml-sparkml-package/blob/master/pom.xml#L81-L141

**Comment by sbourzai** [comment]
It works!! Thank you so much sir for your help

**Comment by sbourzai** [comment]
I'm using pyspark and i want to upgrade the version of jpmml-sparkml, Is it possible ? because after the build there is no egg files
