### ISSUE TITLE
Label field is required and Features field cannot be Vector for Random Forest Regression

### ISSUE THREAD

**Issue by loesak** [jpmml/jpmml-sparkml#18]
I have a generated RandomForestRegressionModel model which was created somewhat similar to that done here: https://spark.apache.org/docs/2.1.0/ml-classification-regression.html#random-forest-regression . The main difference with mine is that the features vector is created using a VectorAssembler and only the generated RandomForestRegressionModel is in the pipeline that i'm trying to export to PMML.

```
PipelineModel model = pipeline.fit(trainingData);

TrainValidationSplitModel tvsm = (TrainValidationSplitModel) model.stages()[0];
RandomForestRegressionModel rfrm = (RandomForestRegressionModel) tvsm.bestModel();

List<Transformer> stages = new ArrayList<>();
stages.add(rfrm);

final PipelineModel pipelineModel = new PipelineModel(
    UUID.randomUUID().toString(),
    stages);

StructType schema = testData.schema();

PMML pmml = ConverterUtil.toPMML(schema, pipelineModel);
```

When trying to export the model to PMML, I get the following exception stating that the label field doesn't exist.

```
Exception in thread "main" java.lang.IllegalArgumentException: Field "label" does not exist.
	at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:264)
	at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:264)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at org.apache.spark.sql.types.StructType.apply(StructType.scala:263)
	at org.jpmml.sparkml.SparkMLEncoder.createDataField(SparkMLEncoder.java:139)
	at org.jpmml.sparkml.SparkMLEncoder.getFeatures(SparkMLEncoder.java:73)
	at org.jpmml.sparkml.SparkMLEncoder.getOnlyFeature(SparkMLEncoder.java:60)
	at org.jpmml.sparkml.ModelConverter.encodeSchema(ModelConverter.java:66)
	at org.jpmml.sparkml.ModelConverter.registerModel(ModelConverter.java:161)
	at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:76)
	at org.loesoft.playground.datascience.mllib.Foo.main(Foo.java:144)
```

Although I know its probably wrong to do this but, I can get around this by adding the the "label" field to the schema however, then I get the following error further down when trying to parse the "features" field with the following exception: 

```
Exception in thread "main" java.lang.IllegalArgumentException: Expected string, integral, double or boolean type, got vector type
	at org.jpmml.sparkml.SparkMLEncoder.createDataField(SparkMLEncoder.java:160)
	at org.jpmml.sparkml.SparkMLEncoder.getFeatures(SparkMLEncoder.java:73)
	at org.jpmml.sparkml.ModelConverter.encodeSchema(ModelConverter.java:140)
	at org.jpmml.sparkml.ModelConverter.registerModel(ModelConverter.java:161)
	at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:76)
	at org.loesoft.playground.datascience.mllib.Foo.main(Foo.java:146)
```

So with this, two things stand out as issues to me. The first is the requirement of the "label" field. I do not believe this is used in the execution of the model so I'm not sure why it is required. The other is the requirement that the "features" field is expected to be a string, integral, double, or boolean when the RandomForestRegressionModel requires it to be a vector.

I'm using version 1.2.2 of jpmml-sparkml and 2.1.1 of spark-mllib_2.11

Bear in mind that I'm fairly new to Spark ML and JPMML so if I am incorrect on this matter, then I would appreciate some education as to where I am wrong.

**Comment by vruusmann** [comment]
> I would appreciate some education as to where I am wrong.

Model schemas are central to the PMML specification. It's about identifying all input and result fields (primary target - eg. predicted class label, and secondary output fields - predicted probability distribution), and their metadata (eg. valid/invalid/missing category levels for categorical fields).

Model schemas make models "portable" in space and time.

Apache Spark ML (just like Scikit-Learn) does not have the concept of a model schema. It is assumed that all the necessary information is hard-coded into the fitted pipeline object, and model portability is achieved by storing and loading the pipeline object in a tightly controlled Apache Spark ML environment.

JPMML-SparkML attempts to "traverse" the fitted pipeline object, and build a proper model schema out of the collected information. The application developer should be aware of that, and act cooperatively by providing necessary label and feature definitions.

> The first is the requirement of the "label" field. I do not believe this is used in the execution of the model so I'm not sure why it is required. 

The label column is used to identify the label (aka target) variable - name, data type, operational type. The last two attributes can be inferred from the model type - `dataType=double opType=continuous` for regression models, and `dataType=string opType=categorical` for classification models.

> The other is the requirement that the "features" field is expected to be a string, integral, double, or boolean when the RandomForestRegressionModel requires it to be a vector

The features column is similarly used to identify input fields. Basically, it must be possible to find out the name, data type and operational type of **_each and every element_** of the feature vector.

The problem is that your synthetic `pipelineModel` object only contains the `rfrm` stage. You should carry over other stages from the original `model` object that describe how the feature vector was assembled - you mention that you were using Spark ML `VectorAssembler` class, but there is no such stage in your `pipelineModel` object (if there were, then JPMML-SparkML would be able to figure out the "composition" of the feature vector).

Have you seen the README file of the JPMML-SparkML-Package project, which exemplifies a simple workflow based on the `RFormula` transformer type? https://github.com/jpmml/jpmml-sparkml-package

If your dataset contains categorical features, then there will be all sorts of vector columns involved behind the scenes, and they are all nicely captured and converted to the PMML data format.

**Comment by loesak** [comment]
Thank you for your quick response.

The original model isn't a Spark ML pipeline at all, it is a TrainValidationSplit model which is not supported by JPMML. I was informed by our DS team that this part of the model isn't needed for model execution, this is why I'm creating a synthetic model (as you noted in your referenced issue). The data transformations to create the features field as a vector is not part of any pipeline but done to the data prior to training, which is what I believe is expected for RandomForestRegression. In fact there is a significant series of transformation that happens to the data prior to training that our model execution code needs to replicate.

I guess what threw me off in the code when i was digging was line 79 in SparkMLEncoder which, at first glance, appears to only allow a string, integer, double, or boolean for a data type for the features column and never a vector. This is invoked on line 140 when attempting to read the features column. I guess I was under the impression that a features column will always be a vector of other data points and never a specific data type.

It sounds like I need much more of an understanding about Spark ML and JPMML before moving forward and that the models we write in Spark ML need to be compatible with JPMML if we want to export them for execution.

Thank you for the information.

**Comment by vruusmann** [comment]
> .. appears to only allow a string, integer, double, or boolean for a data type for the features column and never a vector.

Essentially, JPMML-SparkML expects you to explain how this vector-type feature column was obtained. If you don't provide adequate explanation, then it's impossible to define a stable "model schema", and the whole exercise becomes rather pointless.

Most of the time, this vector-type feature columns is assembled using the `VectorAssembler` meta-transformation right before the model training stage. Some input columns to the vector assembler may be vector-type columns, but if one keeps following this chain, then eventually one should reach scalar-type columns (eg. string, boolean, integer etc).

If the feature vector is prepared by some external data source, then it's possible to trick JPMML-SparkML by creating a synthetic `VectorAssembler` like this:
```
VectorAssembler vectorAssembler = new VectorAssembler()
  .setInputColumns(new String[]{"x1", "x2", "x3"}) // Names of individual vector elements
  .setOutputColumn("featureVector");
```

When invoking JPMML-SparkML, then you would again create a synthetic `PipelineModel`, which has two stages: the above vector assembler stage, and the prediction model stage. You would also need to create a custom `StructType` schema object, which contains "column definitions" for the "x1", "x2" and "x3" fields. The important point is that you may provide whatever column definitions you like (eg. "x1" is a string column, "x2" is a boolean column and "x3" is an integer column), and they would be happily accepted by JPMML-SparkML.

> the transformations to get the feature to a vector are not part of the pipeline. Should they be?

If these transformations are standard Apache Spark ML transformations, then they definitely should be.
