### ISSUE TITLE
jpmml-sparkml with python 3

### ISSUE THREAD

**Issue by SrikantChari** [jpmml/jpmml-sparkml#27]
how do I get mvn -Ppyspark clean package  to use python 3.5 instead of python 2.7?

thank you for your help

**Comment by vruusmann** [comment]
The JPMML-SparkML project has got nothing to do with Python. Perhaps you meant to file this issue with the [JPMML-SparkML-Package](https://github.com/jpmml/jpmml-sparkml-package) project?

If that's the case, then you need to configure your environment properly, so that the command `python` would launch `python3.5` not `python2.7`. Alternatively, you may hard-code the path to appropriate Python executable here:
https://github.com/jpmml/jpmml-sparkml-package/blob/master/pom.xml#L152

**Comment by SrikantChari** [comment]
My apologies, This should have been under  JPMML-SparkML-Package. Thank you for the responding and closing the issue.

**Comment by vruusmann** [comment]
This issue got me thinking, and I've rearranged the `pyspark` build profile so that it's now possible to specify Python executable using the `python.exe` system property.

For example, building first for Python 2.7, and then for Python 3.5:
```
mvn -Ppyspark -Dpython.exe=python2.7 clean install
mvn -Ppyspark -Dpython.exe=python3.5 clean install
```
