### ISSUE TITLE
Can I convert model to pmml?

### ISSUE THREAD

**Issue by Mantj** [jpmml/jpmml-sparkml#85]
I have a GBTClassificationModel, and I want to save it as pmml, but not put it into pipeline, what can I do?
thanks~

**Comment by vruusmann** [comment]
The pipeline wrapper is required, because it holds all sorts of supporting metadata about the learning process (eg. column names).

It should be possible to bypass this "convenience layer", and work directly with lower JPMML-SparkML library layers and APIs. However, I don't have the time to guide you through there.
