### ISSUE TITLE
visualize pmml tree model

### ISSUE THREAD

**Issue by XScarlett** [jpmml/jpmml-sparkml#94]
Is there a better way to visualize PMML tree model?

ths.

**Comment by vruusmann** [comment]
The JPMML software project does not provide any visualization tools right now.

How would you like to visualize if free to choose? Any favourite tools/frameworks/libraries?

I would suggest using some "bridge" data format - instead of developing PMML visualizations tools from scratch, there would simply be a conversion tool that translates PMML models to some already supported data format, which can then be visualized using existing tools.

I know that Scikit-Learn uses [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) data format for tree visualization. So, one way to address this issue would be to build a PMML-to-DOT converter.

**Comment by XScarlett** [comment]
Thanks for your suggestion, i used DOT data format for tree visualization in scikit-learn and performed good, that is what i want, and how can i build a PMML-to-DOT converter?

**Comment by vruusmann** [comment]
> how can i build a PMML-to-DOT converter?

You could develop an XSL stylesheet, or a Java application using the Visitor API of the JPMML-Model library.

The Java application way is probably easier - a new `AbstractVisitor` subclass that prints out a DOT graph vertex every time it visits an `org.dmg.pmml.tree.Node` object.

**Comment by XScarlett** [comment]
> a Java application using the Visitor API of the JPMML-Model library.
> 
> The Java application way is probably easier - a new `AbstractVisitor` subclass that prints out a DOT graph vertex every time it visits an `org.dmg.pmml.tree.Node` object.

I know very little about the Visitor API. Would you help to give me an example? Thanks so much!

**Comment by vruusmann** [comment]
> I know very little about the Visitor API.

It's time to learn something new then!

> Would you help to give me an example?

```java
PMML pmml = ...;

System.out.println("digraph PMML {");
Visitor dotPrinter = new AbstractVisitor(){
  @Override
  public VisitorAction visit(Node node){
    List<Node> children = node.getNodes();
    for(Node child : children){
      System.out.println(node.getId() + " -> " child.getId() + ";");
    }
    return super.visit(node);
  }
};
dotPrinter.applyTo(pmml);
System.out.println("}");
```

Add node attributes as necessary.

**Comment by XScarlett** [comment]
You are a great man, thank you every much!
